name: fracnet
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.8.18
  - pip=22.2.2
  - pytorch-cuda=11.7
  - pytorch=1.13.0
  - torchvision=0.14.0
  - pip:
    - tqdm
    - SimpleITK==1.2.4
    - fastai==1.0.59
    - fastprogress==0.1.21
    - matplotlib==3.1.3
    - nibabel==3.0.0
    - numpy==1.20.0
    - pandas==0.25.3
    - scikit-image==0.16.2
    - tqdm==4.38.0

